In [1]:
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import sys,os

In [3]:
current = os.getcwd()
parrent = os.path.dirname(current)
sys.path.insert(0, parrent)

In [4]:
from scripts.fech_data import fetch_data
from scripts.data_cleaning import preprocess_data
from scripts.visualization import plot_eda

In [5]:
# Define the assets and date range
tickers = ['TSLA', 'BND', 'SPY']
start_date = '2015-01-01'
end_date = '2025-01-31'

In [6]:
data = fetch_data(tickers, start_date, end_date)

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  3 of 3 completed

In [7]:
data

Price           Close                               High              \
Ticker            BND         SPY        TSLA        BND         SPY
Date
2015-01-02  62.573109  172.592880   14.620667  62.603393  173.811114
2015-01-05  62.754795  169.475906   14.006000  62.777507  171.702310
2015-01-06  62.936516  167.879639   14.085333  63.125787  170.316081
2015-01-07  62.974396  169.971619   14.063333  63.050103  170.316085
2015-01-08  62.875973  172.987747   14.041333  62.921396  173.206195
...               ...         ...         ...        ...         ...
2025-01-24  71.805977  607.969971  406.579987  71.855810  610.780029
2025-01-27  72.184738  599.369995  397.149994  72.204677  599.690002
2025-01-28  72.144867  604.520020  398.089996  72.154837  605.369995
2025-01-29  72.104996  601.809998  389.100006  72.254510  604.130005
2025-01-30  72.204674  605.039978  400.279999  72.294378  606.599976

Price                         Low                               Open  \
Ticker            TSLA        BND         SPY        TSLA        BND
Date
2015-01-02   14.883333  62.398976  171.542687   14.217333  62.406549
2015-01-05   14.433333  62.610947  169.165053   13.810667  62.641231
2015-01-06   14.280000  62.860808  167.073085   13.614000  62.860808
2015-01-07   14.318667  62.875977  168.770204   13.985333  62.944112
2015-01-08   14.253333  62.815405  171.383062   14.000667  62.921396
...                ...        ...         ...         ...        ...
2025-01-24  418.880005  71.636531  606.799988  405.779999  71.766106
2025-01-27  406.690002  72.025262  594.640015  389.000000  72.104996
2025-01-28  400.589996  71.975421  597.250000  386.500000  72.154837
2025-01-29  398.589996  71.935550  599.219971  384.480011  72.194707
2025-01-30  412.500000  72.144864  600.719971  384.410004  72.224605

Price                                Volume
Ticker             SPY        TSLA      BND        SPY      TSLA
Date
2015-01-02  173.391037   14.858000  2218800  121465900  71466000
2015-01-05  171.534282   14.303333  5820100  169632600  80527500
2015-01-06  169.786780   14.004000  3887600  209151400  93928500
2015-01-07  169.223882   14.223333  2433400  125346700  44526000
2015-01-08  171.399856   14.187333  1873400  147217800  51637500
...                ...         ...      ...        ...       ...
2025-01-24  609.809998  414.450012  5555700   34604700  56427100
2025-01-27  594.809998  394.799988  8621200   70361100  58125500
2025-01-28  600.619995  396.910004  4424300   44433300  48910700
2025-01-29  603.719971  395.209991  5780200   37177400  68033600
2025-01-30  603.960022  410.779999  5622300   39281300  98092900

[2535 rows x 15 columns]

In [ ]:
data_reset = data.reset_index()

data_reset.columns = [f"{col[0]}_{col[1]}" for col in data.columns]

# Display the renamed data
print(data_reset.head())

In [25]:
data_reset

,Date,Close_BND,Close_SPY,Close_TSLA,High_BND,High_SPY,High_TSLA,Low_BND,Low_SPY,Low_TSLA,Open_BND,Open_SPY,Open_TSLA,Volume_BND,Volume_SPY,Volume_TSLA
0,2015-01-02,62.573109,172.592880,14.620667,62.603393,173.811114,14.883333,62.398976,171.542687,14.217333,62.406549,173.391037,14.858000,2218800,121465900,71466000
1,2015-01-05,62.754795,169.475906,14.006000,62.777507,171.702310,14.433333,62.610947,169.165053,13.810667,62.641231,171.534282,14.303333,5820100,169632600,80527500
2,2015-01-06,62.936516,167.879639,14.085333,63.125787,170.316081,14.280000,62.860808,167.073085,13.614000,62.860808,169.786780,14.004000,3887600,209151400,93928500
3,2015-01-07,62.974396,169.971619,14.063333,63.050103,170.316085,14.318667,62.875977,168.770204,13.985333,62.944112,169.223882,14.223333,2433400,125346700,44526000
4,2015-01-08,62.875973,172.987747,14.041333,62.921396,173.206195,14.253333,62.815405,171.383062,14.000667,62.921396,171.399856,14.187333,1873400,147217800,51637500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2530,2025-01-24,71.805977,607.969971,406.579987,71.855810,610.780029,418.880005,71.636531,606.799988,405.779999,71.766106,609.809998,414.450012,5555700,34604700,56427100
2531,2025-01-27,72.184738,599.369995,397.149994,72.204677,599.690002,406.690002,72.025262,594.640015,389.000000,72.104996,594.809998,394.799988,8621200,70361100,58125500
2532,2025-01-28,72.144867,604.520020,398.089996,72.154837,605.369995,400.589996,71.975421,597.250000,386.500000,72.154837,600.619995,396.910004,4424300,44433300,48910700
2533,2025-01-29,72.104996,601.809998,389.100006,72.254510,604.130005,398.589996,71.935550,599.219971,384.480011,72.194707,603.719971,395.209991,5780200,37177400,68033600
2534,2025-01-30,72.204674,605.039978,400.279999,72.294378,606.599976,412.500000,72.144864,600.719971,384.410004,72.224605,603.960022,410.779999,5622300,39281300,98092900

In [27]:
df = preprocess_data(data_reset)

KeyError: "None of [Index(['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')] are in the [index]"